export interface SeedMiBiblioteca {
  numero: number;   // 10001–10127 (rango exclusivo de mi_biblioteca)
  titulo: string;
  autor: string;
  editorial: string;
  edicion: string;
  idioma: string;   // '' = español
}

export const SEED_MI_BIBLIOTECA: SeedMiBiblioteca[] = [
  { numero: 10001, titulo: "Crimen y Castigo", autor: "Fiodor Dostoievski", editorial: "Editorial San Marcos", edicion: "", idioma: "" },
  { numero: 10002, titulo: "Don Quijote de la Mancha", autor: "Miguel de Cervantes", editorial: "Alfaguara", edicion: "IV CENTENARIO RAE", idioma: "" },
  { numero: 10003, titulo: "La maravillosa historia de Carapuntada", autor: "Guy Bass", editorial: "Molino", edicion: "", idioma: "" },
  { numero: 10004, titulo: "Relatos Esenciales", autor: "Hermann Hesse", editorial: "Sudamericana", edicion: "", idioma: "" },
  { numero: 10005, titulo: "Nuestro Último Verano", autor: "Sebastian Garcia Mouret", editorial: "Alfaguara", edicion: "", idioma: "" },
  { numero: 10006, titulo: "Los 3 Mosqueteros", autor: "Alejandro Dumas", editorial: "Toray", edicion: "10ma Edicion", idioma: "" },
  { numero: 10007, titulo: "Beautiful Disaster", autor: "Jamie McGuire", editorial: "Atria", edicion: "", idioma: "Inglés" },
  { numero: 10008, titulo: "Las Aventuras de Sherlock Holmes", autor: "Arthur Conan Doyle", editorial: "Nostica", edicion: "", idioma: "" },
  { numero: 10009, titulo: "Interworld", autor: "Neil Gaiman y Michael Reaves", editorial: "HarperTeen", edicion: "", idioma: "" },
  { numero: 10010, titulo: "Obras Completas II: Hacia Cero, Pleamares de la Vida, Cinco Cerditos", autor: "Agatha Christie", editorial: "Orbis / Hyspamérica", edicion: "", idioma: "" },
  { numero: 10011, titulo: "Obra Completas II: Trayectoria de Boomerang, El Misterio de Listerdale, Telón", autor: "Agatha Christie", editorial: "Orbis / Hyspamérica", edicion: "", idioma: "" },
  { numero: 10012, titulo: "Dexter Cámara Acción", autor: "Jeff Lindsay", editorial: "Umbriel", edicion: "", idioma: "" },
  { numero: 10013, titulo: "Escrito en el Agua", autor: "Paula Hawkins", editorial: "Planeta", edicion: "", idioma: "" },
  { numero: 10014, titulo: "La Ladrona de Libros", autor: "Markus Zusak", editorial: "Lumen", edicion: "", idioma: "" },
  { numero: 10015, titulo: "La Última Lección", autor: "Randy Pausch y Jeffrey Zaslow", editorial: "Grijalbo", edicion: "", idioma: "" },
  { numero: 10016, titulo: "KimoKawaii", autor: "Enrique Planas", editorial: "Literatura Random House", edicion: "", idioma: "" },
  { numero: 10017, titulo: "Historia del Tiempo", autor: "Stephen W. Hawking", editorial: "Crítica", edicion: "Edicion Especial 25 Aniversario", idioma: "" },
  { numero: 10018, titulo: "Canción Nocturna", autor: "Benjamin Alire Sáenz", editorial: "Destino", edicion: "", idioma: "" },
  { numero: 10019, titulo: "Landline Segundas Oportunidades", autor: "Rainbow Rowell", editorial: "Alfaguara", edicion: "", idioma: "" },
  { numero: 10020, titulo: "Sharpe's Tiger", autor: "Bernard Cornwell", editorial: "Perennial", edicion: "", idioma: "Inglés" },
  { numero: 10021, titulo: "The Meaning of Night", autor: "Michael Cox", editorial: "W.W Norton & Company", edicion: "", idioma: "Inglés" },
  { numero: 10022, titulo: "Diario de Greg 4", autor: "Jeff Kinney", editorial: "Molino Lectorum", edicion: "", idioma: "" },
  { numero: 10023, titulo: "Eleanor & Park", autor: "Rainbow Rowell", editorial: "St. Martin's Griffin", edicion: "", idioma: "" },
  { numero: 10024, titulo: "El Ángel", autor: "Sandrone Dazieri", editorial: "Penguin Random House", edicion: "Primera Edición de Bolsillo", idioma: "" },
  { numero: 10025, titulo: "El Rey Lear, Romeo y Julieta", autor: "William Shakespeare", editorial: "Planeta/EPENSA", edicion: "Biblioteca de Oro", idioma: "" },
  { numero: 10026, titulo: "1984", autor: "George Orwell", editorial: "Lucemar", edicion: "", idioma: "" },
  { numero: 10027, titulo: "Asesinato en el Orient Express", autor: "Agatha Christie", editorial: "RBA", edicion: "Primera Edición de Bolsillo", idioma: "" },
  { numero: 10028, titulo: "Draw Manga Now!: Shojo Basics", autor: "Christopher Hart's", editorial: "Watson Guptill", edicion: "", idioma: "" },
  { numero: 10029, titulo: "Los Miserables I", autor: "Victor Hugo", editorial: "Mercurio", edicion: "", idioma: "" },
  { numero: 10030, titulo: "Los Miserables II", autor: "Victor Hugo", editorial: "Mercurio", edicion: "", idioma: "" },
  { numero: 10031, titulo: "Cien Años de Soledad", autor: "Gabriel García Márquez", editorial: "Sudamericana/Penguin Random House", edicion: "Segunda Edición", idioma: "" },
  { numero: 10032, titulo: "La Jungla de Asfalto", autor: "W.R. Burnett", editorial: "RBA", edicion: "", idioma: "" },
  { numero: 10033, titulo: "Emma", autor: "Jane Austen", editorial: "Biblok", edicion: "Colección Selecta", idioma: "" },
  { numero: 10034, titulo: "Malditas Matemáticas: Alicia en el País de los Números", autor: "Carlo Frabetti", editorial: "Alfaguara Juvenil", edicion: "", idioma: "" },
  { numero: 10035, titulo: "La Chica del Tren", autor: "Paula Hawkins", editorial: "Planeta", edicion: "", idioma: "" },
  { numero: 10036, titulo: "Demian", autor: "Herman Hesse", editorial: "Gernika/PubliMexi", edicion: "", idioma: "" },
  { numero: 10037, titulo: "La Proporción Áurea", autor: "National Geographic", editorial: "RBA", edicion: "National Geographic", idioma: "" },
  { numero: 10038, titulo: "Matemáticos, Espías y Piratas Informáticos", autor: "National Geographic", editorial: "RBA", edicion: "National Geographic", idioma: "" },
  { numero: 10039, titulo: "Zelda", autor: "RBA", editorial: "RBA", edicion: "Videojuegos Legendarios", idioma: "" },
  { numero: 10040, titulo: "Super Mario", autor: "RBA", editorial: "RBA", edicion: "Videojuegos Legendarios", idioma: "" },
  { numero: 10041, titulo: "Historia de un muerto contado por él Mismo", autor: "Alejandro Dumas", editorial: "Planeta", edicion: "Clásicos de Terror", idioma: "" },
  { numero: 10042, titulo: "El Invencible Iron Man: El Origen", autor: "Marvel", editorial: "Marvel", edicion: "", idioma: "" },
  { numero: 10043, titulo: "Shojo Fashio Maga Art School", autor: "Irene Flores", editorial: "Impact", edicion: "", idioma: "" },
  { numero: 10044, titulo: "El Gran Gatsby", autor: "F. Scott Fitzgerald", editorial: "Plutón", edicion: "Colección Eterna", idioma: "" },
  { numero: 10045, titulo: "Harry Potter y la Piedra Filosofal 1", autor: "J.K. Rowling", editorial: "Salamandra", edicion: "", idioma: "" },
  { numero: 10046, titulo: "Harry Potter y la Cámara Secreta 2", autor: "J.K. Rowling", editorial: "Salamandra", edicion: "", idioma: "" },
  { numero: 10047, titulo: "Harry Potter y el Prisionero de Azkaban 3", autor: "J.K. Rowling", editorial: "Salamandra", edicion: "", idioma: "" },
  { numero: 10048, titulo: "Harry Potter y el Cáliz de Fuego 4", autor: "J.K. Rowling", editorial: "Salamandra", edicion: "", idioma: "" },
  { numero: 10049, titulo: "Harry Potter y la Orden del Fénix 5", autor: "J.K. Rowling", editorial: "Salamandra", edicion: "", idioma: "" },
  { numero: 10050, titulo: "Harry Potter y el Misterio del Príncipe 6", autor: "J.K. Rowling", editorial: "Salamandra", edicion: "", idioma: "" },
  { numero: 10051, titulo: "Quidditch a Través de los Tiempos", autor: "Kennilworthy Whisp", editorial: "Salamandra", edicion: "", idioma: "" },
  { numero: 10052, titulo: "Peter Pan", autor: "James Matthew Barrie", editorial: "Tomo", edicion: "Clásicos Juveniles", idioma: "" },
  { numero: 10053, titulo: "El Vagón de las Mujeres", autor: "Anita Nair", editorial: "Punto de Lectura", edicion: "", idioma: "" },
  { numero: 10054, titulo: "Viajes de Gulliver", autor: "Jonathan Swift", editorial: "Salvat/alianza Editorial", edicion: "Biblioteca Básica Salvat", idioma: "" },
  { numero: 10055, titulo: "La Abadía de Northanger", autor: "Jane Austen", editorial: "Penguin Random House", edicion: "Penguin Clásicos", idioma: "" },
  { numero: 10056, titulo: "Travesuras de una Niña Mala", autor: "Mario Vargas Llosa", editorial: "Alfaguara", edicion: "", idioma: "" },
  { numero: 10057, titulo: "Y de repente un Ángel", autor: "Jaime Bayly", editorial: "Planeta", edicion: "", idioma: "" },
  { numero: 10058, titulo: "La mujer de mi hermano", autor: "Jaime Bayly", editorial: "Planeta", edicion: "", idioma: "" },
  { numero: 10059, titulo: "El Cuaderno de Maya", autor: "Isabel Allende", editorial: "Copia", edicion: "", idioma: "" },
  { numero: 10060, titulo: "Vero y los Piratas de la Malasia", autor: "Carlos Puerto y Jordi Vila Delclos", editorial: "Eldelvives", edicion: "", idioma: "" },
  { numero: 10061, titulo: "Vero y la Corte del Rey Arturo", autor: "Carlos Puerto y Jordi Vila Delclos", editorial: "Eldelvives", edicion: "", idioma: "" },
  { numero: 10062, titulo: "Insignia", autor: "S.J. Kincaid", editorial: "V&R", edicion: "", idioma: "" },
  { numero: 10063, titulo: "Vortex", autor: "S.J. Kincaid", editorial: "Katherin Tengen Books", edicion: "", idioma: "Inglés" },
  { numero: 10064, titulo: "La Casa de los Espíritus", autor: "Isabel Allende", editorial: "Copia", edicion: "", idioma: "" },
  { numero: 10065, titulo: "El Arroyo de la Llorona y otros cuentos", autor: "Sandra Cisneros", editorial: "Vintage Español", edicion: "", idioma: "" },
  { numero: 10066, titulo: "Preguntas y Problemas de Física", autor: "L.Tarásov, A.Tarásov", editorial: "Mir Moscú", edicion: "", idioma: "" },
  { numero: 10067, titulo: "El Pudding de Navidad", autor: "Agatha Christie", editorial: "Molino", edicion: "Biblioteca Oro", idioma: "" },
  { numero: 10068, titulo: "Antología Poética / A Propósito de Rubén Darío y su Obra", autor: "Rubén Darío", editorial: "Cara Cruz", edicion: "", idioma: "" },
  { numero: 10069, titulo: "Don Quijote de la Mancha Tomo III", autor: "Miguel de Cervantes", editorial: "RBA", edicion: "", idioma: "" },
  { numero: 10070, titulo: "Las Aventuras de Sherlock Holmes", autor: "Arthur Conan Doyle", editorial: "EDAF", edicion: "Edición de Alejandro Pareja", idioma: "" },
  { numero: 10071, titulo: "Love Story", autor: "Erich Segal", editorial: "Círculo de Lectores", edicion: "", idioma: "" },
  { numero: 10072, titulo: "El conde de Lucanor", autor: "Don Juan Manuel", editorial: "", edicion: "", idioma: "" },
  { numero: 10073, titulo: "La Metamorfosis", autor: "Franz Kafka", editorial: "Copia", edicion: "", idioma: "" },
  { numero: 10074, titulo: "River of Death", autor: "Alistar Maclean", editorial: "Fawcett Crest", edicion: "", idioma: "Inglés" },
  { numero: 10075, titulo: "La Casa Torcida", autor: "Agatha Christie", editorial: "Molino", edicion: "Selecciones de Biblioteca Oro", idioma: "" },
  { numero: 10076, titulo: "El Misterioso Mr.Brown", autor: "Agatha Christie", editorial: "Planeta", edicion: "", idioma: "" },
  { numero: 10077, titulo: "Cuando Éramos Mayores", autor: "Anne Tyler", editorial: "Punto de Lectura", edicion: "", idioma: "" },
  { numero: 10078, titulo: "Narraciones Extraordinarias", autor: "Edgar Allan Poe", editorial: "Terramar", edicion: "Clásicos de la Literatura Fantástica", idioma: "" },
  { numero: 10079, titulo: "El Jugador", autor: "Fiodor Dostoievski", editorial: "Servilibro", edicion: "Literatura Universal", idioma: "" },
  { numero: 10080, titulo: "La Cúpula Parte 1", autor: "Stephen King", editorial: "Penguin Random House", edicion: "Sudamericana", idioma: "" },
  { numero: 10081, titulo: "Los Ojos de mi Princesa / La fuerza de Sheccid", autor: "Carlos Cuauhtémoc Sánchez", editorial: "Copia", edicion: "", idioma: "" },
  { numero: 10082, titulo: "I Fell Quiz del Mago Wiz", autor: "Brand Parker y Johnny Hart", editorial: "Arnoldo Mondadori", edicion: "", idioma: "Italiano" },
  { numero: 10083, titulo: "Cuchilla", autor: "Evelio José Rosero", editorial: "Norma", edicion: "Colección Torre de Papel Azul", idioma: "" },
  { numero: 10084, titulo: "Rumpole's Last Case", autor: "John Mortimer", editorial: "Penguin Books", edicion: "", idioma: "Inglés" },
  { numero: 10085, titulo: "La Palabra del Mudo", autor: "Julio Ramon Ribeyro", editorial: "Sociedad Literaria", edicion: "Antología", idioma: "" },
  { numero: 10086, titulo: "Metafísica", autor: "Conny Mendez", editorial: "Bienes Lacónica", edicion: "", idioma: "" },
  { numero: 10087, titulo: "Metafísica", autor: "Conny Mendez", editorial: "Copia", edicion: "", idioma: "" },
  { numero: 10088, titulo: "Los Gallinazos sin Plumas y otros cuentos peruanos", autor: "Julio Ramon Ribeyro", editorial: "Impacto Cultural", edicion: "Plan Lector Cuentos Escolares", idioma: "" },
  { numero: 10089, titulo: "El Conde de Montecristo", autor: "Alejandro Dumas", editorial: "Ediciones Cultura Peruana", edicion: "Cuadernos Catedráticos", idioma: "" },
  { numero: 10090, titulo: "La Divina Comedia", autor: "Dante", editorial: "Ediciones Ibéricas", edicion: "Octava Edición", idioma: "" },
  { numero: 10091, titulo: "Me Dicen Sra Tomate", autor: "Jean Ure", editorial: "Norma", edicion: "", idioma: "" },
  { numero: 10092, titulo: "Colmillo Blanco", autor: "Jack London", editorial: "Impacto Cultural", edicion: "Plan Lector Cuentos Escolares", idioma: "" },
  { numero: 10093, titulo: "Ollantay", autor: "Anónimo", editorial: "Didacta", edicion: "Biblioteca Básica Escolar", idioma: "" },
  { numero: 10094, titulo: "Mi Planta de Naranja Lima", autor: "José Mauro de Vasconcelos", editorial: "Copia", edicion: "Edición Completa", idioma: "" },
  { numero: 10095, titulo: "Poema del Cid", autor: "", editorial: "Editorial Universo", edicion: "", idioma: "" },
  { numero: 10096, titulo: "Nueve Colores Sangra la Luna", autor: "Carlos Aguilar", editorial: "La Factoría", edicion: "", idioma: "" },
  { numero: 10097, titulo: "Drácula", autor: "Bram Stoker", editorial: "Septiembre", edicion: "", idioma: "" },
  { numero: 10098, titulo: "Se Anuncia un Asesinato", autor: "Agatha Christie", editorial: "RBA", edicion: "", idioma: "" },
  { numero: 10099, titulo: "Bueno, Bonito y Barato Tomo 1", autor: "Rolando Arellano", editorial: "Planeta", edicion: "", idioma: "" },
  { numero: 10100, titulo: "Una Dama Extraviada", autor: "Willa Cather", editorial: "Alba Editorial", edicion: "", idioma: "" },
  { numero: 10101, titulo: "Ghostgirl", autor: "Tonya Hurley", editorial: "Copia", edicion: "", idioma: "" },
  { numero: 10102, titulo: "Cuentos Breves para Leer", autor: "Maximiliano Tomas", editorial: "Norma", edicion: "", idioma: "" },
  { numero: 10103, titulo: "Sentido y Sensibilidad y Monstruos Marinos", autor: "Jane Austen y Ben H. Winters", editorial: "Umbriel Editores", edicion: "", idioma: "" },
  { numero: 10104, titulo: "El Principito", autor: "Antoine De Saint Exupery", editorial: "Corporación Editora Chirre", edicion: "", idioma: "" },
  { numero: 10105, titulo: "Los ojos de mi Princesa 2", autor: "Carlos Cuauhtémoc Sánchez", editorial: "Copia", edicion: "", idioma: "" },
  { numero: 10106, titulo: "La Vida es Sueño", autor: "Calderón de la Barca", editorial: "Toribio Anyarin Injante", edicion: "", idioma: "" },
  { numero: 10107, titulo: "Bodas de Sangre", autor: "Federico García Lorca", editorial: "Fondo Editorial Cultura Peruana", edicion: "", idioma: "" },
  { numero: 10108, titulo: "Ña Catita", autor: "Manuel A. Segura", editorial: "Ediciones Cultura Peruana", edicion: "", idioma: "" },
  { numero: 10109, titulo: "La Bruja de Portobello", autor: "Paulo Coelho", editorial: "Planeta", edicion: "", idioma: "" },
  { numero: 10110, titulo: "Taita Cristo y otros cuentos escolares", autor: "Eleodoro Vargas Vicuña", editorial: "Fondo Editorial Cultura Peruana", edicion: "", idioma: "" },
  { numero: 10111, titulo: "Veronika Decide Morir", autor: "Paulo Coelho", editorial: "Copia", edicion: "", idioma: "" },
  { numero: 10112, titulo: "La Última Noche", autor: "Rainbow Rowell", editorial: "Alfaguara", edicion: "", idioma: "" },
  { numero: 10113, titulo: "La Cabaña", autor: "W. Paul Young", editorial: "Copia", edicion: "", idioma: "" },
  { numero: 10114, titulo: "Heridas Abiertas", autor: "Gillian Flynn", editorial: "Copia", edicion: "", idioma: "" },
  { numero: 10115, titulo: "Perdida", autor: "Gillian Flynn", editorial: "Copia", edicion: "", idioma: "" },
  { numero: 10116, titulo: "Phoebe and her Unicorn in Unicorn Theater", autor: "Dana Simpson", editorial: "Andrews McMeel", edicion: "", idioma: "" },
  { numero: 10117, titulo: "Unicorn Bowling", autor: "Dana Simpson", editorial: "Andrews McMeel", edicion: "", idioma: "" },
  { numero: 10118, titulo: "Diario de Greg 6", autor: "Jeff Kinney", editorial: "Copia", edicion: "", idioma: "" },
  { numero: 10119, titulo: "Diario de Greg 5", autor: "Jeff Kinney", editorial: "Copia", edicion: "", idioma: "" },
  { numero: 10120, titulo: "Diario de Greg 3", autor: "Jeff Kinney", editorial: "Copia", edicion: "", idioma: "" },
  { numero: 10121, titulo: "Diario de Greg 2", autor: "Jeff Kinney", editorial: "Copia", edicion: "", idioma: "" },
  { numero: 10122, titulo: "Diario de Greg 1", autor: "Jeff Kinney", editorial: "Copia", edicion: "", idioma: "" },
  { numero: 10123, titulo: "Buenos Dias Princesa", autor: "Blue Jeans", editorial: "Copia", edicion: "", idioma: "" },
  { numero: 10124, titulo: "Diario de una Friki 1", autor: "Anna Cammany", editorial: "Copia", edicion: "", idioma: "" },
  { numero: 10125, titulo: "Diario de una Friki 2", autor: "Anna Cammany", editorial: "Copia", edicion: "", idioma: "" },
  { numero: 10126, titulo: "Diario de una Friki 3", autor: "Anna Cammany", editorial: "Copia", edicion: "", idioma: "" },
  { numero: 10127, titulo: "Las Ventajas de ser Invisible", autor: "Stephen Chbosky", editorial: "Alfaguara", edicion: "", idioma: "" },
];
